// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChO5wuva19uo0twgeIPL7PsevcpnLsstc',
    appId: '1:121121875222:web:2d9ebfcaa7377e5a3f9c37',
    messagingSenderId: '121121875222',
    projectId: 'smartkost-a6460',
    authDomain: 'smartkost-a6460.firebaseapp.com',
    storageBucket: 'smartkost-a6460.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlTsvJH_rQwaAYeElLzaP9sWFAHXztZI',
    appId: '1:121121875222:android:c1ccd049cc5660fb3f9c37',
    messagingSenderId: '121121875222',
    projectId: 'smartkost-a6460',
    storageBucket: 'smartkost-a6460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeoWDI9iI1xzElR49Fh0ucXRvMR6eHuJs',
    appId: '1:121121875222:ios:b047a741d4b955103f9c37',
    messagingSenderId: '121121875222',
    projectId: 'smartkost-a6460',
    storageBucket: 'smartkost-a6460.firebasestorage.app',
    iosBundleId: 'com.example.smartkostAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeoWDI9iI1xzElR49Fh0ucXRvMR6eHuJs',
    appId: '1:121121875222:ios:b047a741d4b955103f9c37',
    messagingSenderId: '121121875222',
    projectId: 'smartkost-a6460',
    storageBucket: 'smartkost-a6460.firebasestorage.app',
    iosBundleId: 'com.example.smartkostAplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChO5wuva19uo0twgeIPL7PsevcpnLsstc',
    appId: '1:121121875222:web:6b9fb28fb8f2171f3f9c37',
    messagingSenderId: '121121875222',
    projectId: 'smartkost-a6460',
    authDomain: 'smartkost-a6460.firebaseapp.com',
    storageBucket: 'smartkost-a6460.firebasestorage.app',
  );
}
